default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: myuser
  password: mypass

development:
  <<: *default
  database: templaterb_development

test:
  <<: *default
  database: templaterb_test

production:
  <<: *default
  database: templaterb_production
  username: templaterb
  password: <%= ENV["TEMPLATERB_DATABASE_PASSWORD"] %>
